USE [master]
GO
/****** Object:  Database [ContactManagement]    Script Date: 17-01-2022 04:22:09 PM ******/
CREATE DATABASE [ContactManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ContactManagement', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ContactManagement.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ContactManagement_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ContactManagement_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ContactManagement] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ContactManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ContactManagement] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ContactManagement] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ContactManagement] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ContactManagement] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ContactManagement] SET ARITHABORT OFF 
GO
ALTER DATABASE [ContactManagement] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ContactManagement] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ContactManagement] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ContactManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ContactManagement] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ContactManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ContactManagement] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ContactManagement] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ContactManagement] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ContactManagement] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ContactManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ContactManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ContactManagement] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ContactManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ContactManagement] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ContactManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ContactManagement] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ContactManagement] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ContactManagement] SET  MULTI_USER 
GO
ALTER DATABASE [ContactManagement] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ContactManagement] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ContactManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ContactManagement] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [ContactManagement] SET DELAYED_DURABILITY = DISABLED 
GO
USE [ContactManagement]
GO
/****** Object:  Table [dbo].[Contacts]    Script Date: 17-01-2022 04:22:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Contacts](
	[ContactId] [bigint] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[EmailId] [varchar](50) NOT NULL,
	[MobileNumber] [varchar](50) NOT NULL,
	[Status] [bit] NOT NULL,
 CONSTRAINT [PK_Contacts] PRIMARY KEY CLUSTERED 
(
	[ContactId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
USE [master]
GO
ALTER DATABASE [ContactManagement] SET  READ_WRITE 
GO
